export const baseColorInput = document.getElementById("base-color-input");
export const surfaceColorInput = document.getElementById('surface-color-input');
export const brandColorInput = document.getElementById('main-color-input');
export const textColorInput = document.getElementById('text-color-input');
export const textSecondaryInput = document.getElementById('text-secondary-input');
brandColorInput.value = "#0d57c7";
baseColorInput.value = "#010101";
surfaceColorInput.value = "#272727";
textColorInput.value = "#f9f9f9";
textSecondaryInput.value = "#cfcdcd"
